[dio]
install_dir = /var/mnt/lentao/dio_shared
state_db = /run/media/system/HERMES/.hermes/state.db
database = /var/mnt/lentao/dio_shared/dio_knowledge.db
auto_recomend_storage = true
cron_rebuild = true
lang = pt
installed_at = 2026-09-04 11:00
